// Frontend/react/src/Components/Login/Login.jsx
import {
    Button,
    Checkbox,
    Flex,
    FormControl,
    FormLabel,
    Heading,
    Input,
    Link,
    Stack,
    Image,
    Text,
    Box,
    Alert,
    AlertIcon
  } from '@chakra-ui/react';
import { Formik,Form,useField } from 'formik';
import * as Yup from 'yup';
import { useAuth } from '../context/AuthContext';
import { errorNotification } from '../../services/notification';
import { useNavigate } from 'react-router-dom';
import { useEffect } from 'react';


const MyTextInput = ({ label, ...props }) => {
  // useField() returns [formik.getFieldProps(), formik.getFieldMeta()]
  // which we can spread on <input>. We can use field meta to show an error
  // message if the field is invalid and it has been touched (i.e. visited)
  const [field, meta] = useField(props);
  return (
    <Box>
      <FormLabel htmlFor={props.id || props.name}>{label}</FormLabel>
      <Input className="text-input" {...field} {...props} />
      {meta.touched && meta.error ? (
        <Alert className="error" status={"error"} mt={2}>
            <AlertIcon/>
            {meta.error}
            </Alert>
      ) : null}
    </Box>
  );
};


  const LoginForm = ()=>{
    const {login} = useAuth();
    const navigate = useNavigate();
    return (
      <Formik
        initialValues={{username: "",password: ""}}
        validationSchema={Yup.object({
          username: Yup.string()
          .email("Must be valid email")
          .required('Email is required'),
          password:Yup.string().max(30,"password cannot be more than 20 characters")
            .required("Password is required")
        })
      
      }
        validateOnMount={true}
        onSubmit={(values,{setSubmitting})=>{
          setSubmitting(true);
          login(values).then(res=>{
            navigate("/dashboard");
          }).catch(err=>
            {
            
            errorNotification(err.code,
              err.response.data.message
            )}
          ).finally(()=>{
            setSubmitting(false);
          })
        }}>
          {({isValid,isSubmitting})=>(
            <Form>
              <Stack spacing={15}>
                <MyTextInput label={"Email"} name= {"username"} type= {"email"} placeholder={"hello@examole.com"}/>

                <MyTextInput label={"Passowrd"} name= {"password"} type= {"password"} placeholder={"Type your passord"}/>

                <Button isDisabled={!isValid || isSubmitting} type='submit'> Login</Button>
              </Stack>
            </Form>

          )}
        </Formik>
    )
  }
  
  export default function Login() {
    const {customer} = useAuth();
    const navigate = useNavigate();
    useEffect(()=>{
      if(customer){
        navigate("/dashboard");
      }
    })
    return (
      <Stack minH={'100vh'} direction={{ base: 'column', md: 'row' }}>
        <Flex p={8} flex={1} align={'center'} justify={'center'}>
          <Stack spacing={4} w={'full'} maxW={'md'}>
            <Heading fontSize={'2xl'} mb={15}>Sign in to your account</Heading>
            <LoginForm/>
            <Link color={"blue.500"} href='/signup'>Dont have an account? Sign up now.</Link>
          </Stack>
        </Flex>
        <Flex flex={1} p={10} flexDirection={"column"} alignItems={"center"} justifyContent={"center"} bgGradient={{sm:"linear(to-r,blue.600, purple.600)"}}>
          <Stack margin={"auto"}>
          <Text fontSize={"5xl"} color={'white'} fontWeight={"bold"} mb={5} m={"auto"}>
              <Link href='https://github.com/ghadyg'>
                Checkout my github
              </Link>
          </Text>
          <Image
            alt={'Login Image'}
            objectFit={'cover'}
            src={
              'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1352&q=80'
            }
          />
          </Stack>
        </Flex>
      </Stack>
    );
  }

// Frontend/angular/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { AuthenticationRequest } from '../../models/authentication-request';
import { AuthenticationService } from '../../services/authentication/authentication.service';
import { Message } from 'primeng/api';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrl: './login.component.scss'
})
export class LoginComponent {
SignUp() {
    this.router.navigate(["signup"]);
}
message: Message[] = [];
  constructor(private authenticationService: AuthenticationService,
    private router:Router
  ){}

  errorMsg:string = "";

  login() {
    this.message =[];
  this.authenticationService.login(this.authentication)
  .subscribe({
    next: (authenticationResponse)=>{
      localStorage.setItem('token',JSON.stringify(authenticationResponse));
      this.router.navigate(["customer"]);   
    },
    error: (err)=>{
      if(err.error.statusCode===401)
        {
          
          this.message = [{
            detail:'Username or password are incorrect',
            severity:"error"
          }]
        }
    }
  }
)
  ;
  }

  authentication: AuthenticationRequest = {};

}

<div class="flex" style="height: 100vh;">
    <div class="col-6 m-3 flex flex-column justify-content-center" >
        <div class="m-auto">
        <div class="text-center">
            <h1>Sign in to your account</h1>
        </div>
        <p-messages [(value)]="message" />
        <div class="field">
            <label for="Email">Email</label>
            <input
            id="Email"
            pInputText
            placeholder="Jane@gmail.com"
            [(ngModel)]="authentication.username"
            type="email"
            class="w-full"
            /> 
         </div>
         <div class="field">
            <label for="password">Passowrd</label>
            <input
            id="password"
            pInputText
            placeholder=""
            [(ngModel)]="authentication.password"
            type="password"
            class="w-full"
            /> 
        </div>
        
        <button pButton label="Submit" class="w-full"
        (click)="login()"
        ></button>
        <button pButton
        class="w-full p-button-link pl-0 text-left"
        label="Don't have an account? Signup now"
        (click)="SignUp()"
        ></button>
        </div>
    </div>
    <div class="col-6 flex flex-column justify-content-center align-items-center right-container" >
        <h1>
            <a href='https://github.com/ghadyg' target="_blank">Checkout my github</a>
        </h1>
        <img src='https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1352&q=80'
        class="background p-6 pt-0"
        />
    </div>
</div>
